# Numpy

libreria para el trabajo de vectores y matrices

$$ \frac{a}{x^b} $$

In [2]:
import numpy as np

In [3]:
a = np.zeros((4,5))

In [4]:
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
lista = [1,2,3,4,5]
type (lista)
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
a = np.array(lista)

In [8]:
a

array([1, 2, 3, 4, 5])

In [9]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
a = np.eye((3))
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
b = np.ones((3,3))

In [13]:
b


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
a +b 

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [15]:
c = a + b

In [16]:
c

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [17]:
c * 2

array([[4., 2., 2.],
       [2., 4., 2.],
       [2., 2., 4.]])

In [18]:
c / 2

array([[1. , 0.5, 0.5],
       [0.5, 1. , 0.5],
       [0.5, 0.5, 1. ]])

In [19]:
c ** 2

array([[4., 1., 1.],
       [1., 4., 1.],
       [1., 1., 4.]])

In [20]:
a = np.array([[1,1],[0,1]])
b = np.array([[1,0],[1,1]])
a
b

array([[1, 0],
       [1, 1]])

In [21]:
b

array([[1, 0],
       [1, 1]])

In [22]:
a

array([[1, 1],
       [0, 1]])

In [23]:
a * b

array([[1, 0],
       [0, 1]])

In [24]:
np.dot(a,b)

array([[2, 1],
       [1, 1]])

In [25]:
a

array([[1, 1],
       [0, 1]])

In [26]:
b

array([[1, 0],
       [1, 1]])

In [27]:
a.dot(b)

array([[2, 1],
       [1, 1]])

In [28]:
a @ b

array([[2, 1],
       [1, 1]])

In [29]:
g = np.array([.5,0.,1,.33])
np.sin(g)

array([0.47942554, 0.        , 0.84147098, 0.32404303])

In [30]:
g.size()

TypeError: 'int' object is not callable

In [31]:
np.size(g)

4

In [32]:
np.size (a)

4

In [33]:
np.shape(g)

(4,)

In [34]:
np.shape(a)

(2, 2)

In [35]:
a

array([[1, 1],
       [0, 1]])

In [36]:
np.linalg.inv(a)

array([[ 1., -1.],
       [ 0.,  1.]])

In [40]:
a=np.array([[2,1,-1],[-3,-1,2],[-2,1,2]])
b=np.array([8,-11,-3])

In [41]:
np.linalg.solve(a,b)

array([ 2.,  3., -1.])

In [45]:
from numpy.linalg import solve, inv


In [46]:
solve (a,b)

array([ 2.,  3., -1.])

In [47]:
inv(a)

array([[ 4.,  3., -1.],
       [-2., -2.,  1.],
       [ 5.,  4., -1.]])

In [48]:
a

array([[ 2,  1, -1],
       [-3, -1,  2],
       [-2,  1,  2]])

In [49]:
a[1,1]

-1

In [50]:
a[1,:]

array([-3, -1,  2])

In [51]:
a[1,:] = a[1,:] / 2.0

In [52]:
a

array([[ 2,  1, -1],
       [-1,  0,  1],
       [-2,  1,  2]])

In [53]:
a=np.array([[2.,1.,-1.],[-3.,-1.,2.],[-2.,1.,2.]])

In [54]:
a

array([[ 2.,  1., -1.],
       [-3., -1.,  2.],
       [-2.,  1.,  2.]])

In [55]:
a[1,:] = a[1,:] / 2.0

In [56]:
a

array([[ 2. ,  1. , -1. ],
       [-1.5, -0.5,  1. ],
       [-2. ,  1. ,  2. ]])

In [57]:
a[1:2,1:2] = a[1:2,1:2] * 3.0

In [58]:
a

array([[ 2. ,  1. , -1. ],
       [-1.5, -1.5,  1. ],
       [-2. ,  1. ,  2. ]])

In [63]:
b = a[1:2,1:2] * 3.0
b

array([[-4.5]])

In [64]:
np.random.rand()

0.5641303945480844

In [66]:
np.random.randint(1,10)

3

In [68]:
np.random.rand(2,3)

array([[0.7337721 , 0.6089355 , 0.73992302],
       [0.22565138, 0.87445505, 0.98971807]])

In [86]:
lista = array([1,2,3,4,5,6])
np.random.choice(lista)

2

In [92]:
lista = np.array([1,2,3,4,5,6])
np.random.permutation(lista)

array([4, 5, 3, 1, 2, 6])